import type {
  Exam,
  Teacher,
  Question,
  QuestionGroup,
  ExamRequest,
  StudentSession,
  Student,
  User,
  AuditLog,
} from "./types"

// Current logged-in user (can be changed for demo)
export const currentUser: User = {
  id: "1",
  name: "Dr. Sarah Johnson",
  email: "sarah.johnson@university.edu",
  role: "teacher",
  department: "Computer Science",
}

// Mock students with comprehensive data
export const students: Student[] = [
  {
    id: "231001001447",
    name: "John Doe",
    email: "john.doe@student.edu",
    batch: "BSCS-2021",
    course: "BSCS",
    department: "Computer Science",
    year: 2021,
  },
  {
    id: "231001001448",
    name: "Jane Smith",
    email: "jane.smith@student.edu",
    batch: "BSCS-2021",
    course: "BSCS",
    department: "Computer Science",
    year: 2021,
  },
  {
    id: "231001001449",
    name: "Mike Johnson",
    email: "mike.johnson@student.edu",
    batch: "BSCS-2022",
    course: "BSCS",
    department: "Computer Science",
    year: 2022,
  },
  {
    id: "231001001450",
    name: "Alice Brown",
    email: "alice.brown@student.edu",
    batch: "BSCS-2021",
    course: "BSCS",
    department: "Computer Science",
    year: 2021,
  },
  {
    id: "231001001451",
    name: "Bob Wilson",
    email: "bob.wilson@student.edu",
    batch: "BSCS-2023",
    course: "BSCS",
    department: "Computer Science",
    year: 2023,
  },
  {
    id: "231001001452",
    name: "Emma Davis",
    email: "emma.davis@student.edu",
    batch: "BSCS-2021",
    course: "BSCS",
    department: "Computer Science",
    year: 2021,
  },
  {
    id: "231001001453",
    name: "David Lee",
    email: "david.lee@student.edu",
    batch: "BSCS-2022",
    course: "BSCS",
    department: "Computer Science",
    year: 2022,
  },
  {
    id: "231001001454",
    name: "Sarah Connor",
    email: "sarah.connor@student.edu",
    batch: "BSCS-2023",
    course: "BSCS",
    department: "Computer Science",
    year: 2023,
  },
]

// Current logged-in teacher (mock)
export const currentTeacherMock: Teacher = {
  id: 1,
  name: "Dr. Sarah Johnson",
  email: "sarah.johnson@university.edu",
  subjects: [1, 2, 3],
  department: "Computer Science",
}

// Mock data for subjects
export const assignedSubjects = [
  { id: 1, code: "CS101", name: "Introduction to Programming", department: "Computer Science", course: "BSCS" },
  { id: 2, code: "CS201", name: "Data Structures", department: "Computer Science", course: "BSCS" },
  { id: 3, code: "CS301", name: "Database Systems", department: "Computer Science", course: "BSCS" },
  { id: 4, code: "MATH101", name: "Calculus I", department: "Mathematics", course: "BSCS" },
  { id: 5, code: "CS401", name: "Software Engineering", department: "Computer Science", course: "BSCS" },
  { id: 6, code: "CS501", name: "Machine Learning", department: "Computer Science", course: "BSCS" },
]

// Mock data for teachers (for invigilator selection)
export const teachers: Teacher[] = [
  currentTeacherMock,
  {
    id: 2,
    name: "Prof. Michael Chen",
    email: "michael.chen@university.edu",
    subjects: [2, 3],
    department: "Computer Science",
  },
  { id: 3, name: "Dr. Emily Davis", email: "emily.davis@university.edu", subjects: [1, 4], department: "Mathematics" },
  {
    id: 4,
    name: "Prof. James Wilson",
    email: "james.wilson@university.edu",
    subjects: [3, 5],
    department: "Computer Science",
  },
  {
    id: 5,
    name: "Dr. Lisa Anderson",
    email: "lisa.anderson@university.edu",
    subjects: [6],
    department: "Computer Science",
  },
]

// Question-bank constants
export const questionTypes = [
  { id: "mcq", name: "Multiple Choice" },
  { id: "true_false", name: "True/False" },
  { id: "short_answer", name: "Short Answer" },
  { id: "descriptive", name: "Descriptive" },
  { id: "fill_blank", name: "Fill in the Blank" },
  { id: "matching", name: "Matching" },
]

export const difficultyLevels = [
  { id: "easy", name: "Easy" },
  { id: "medium", name: "Medium" },
  { id: "hard", name: "Hard" },
]

// Comprehensive mock questions for testing pagination (50 questions total)
export const initialQuestions: Question[] = [
  // Database Systems Questions (1-15)
  {
    id: 1,
    text: "What is a database management system (DBMS)?",
    type: "descriptive",
    subject: 3,
    difficulty: "medium",
    marks: 5,
    createdAt: "2023-05-15T10:30:00Z",
    updatedAt: "2023-05-15T10:30:00Z",
    createdBy: "1",
    status: "active",
    tags: ["database", "dbms", "introduction"],
    answer:
      "A database management system (DBMS) is software that handles the storage, retrieval, and management of data in a database.",
  },
  {
    id: 2,
    text: "Which of the following is NOT a type of database?",
    type: "mcq",
    subject: 3,
    difficulty: "easy",
    marks: 2,
    createdAt: "2023-05-16T14:45:00Z",
    updatedAt: "2023-05-16T14:45:00Z",
    createdBy: "1",
    status: "active",
    tags: ["database", "types"],
    options: [
      { id: 1, text: "Relational Database", isCorrect: false },
      { id: 2, text: "NoSQL Database", isCorrect: false },
      { id: 3, text: "Object-Oriented Database", isCorrect: false },
      { id: 4, text: "Binary Database", isCorrect: true },
    ],
  },
  {
    id: 3,
    text: "Explain the concept of normalization in databases.",
    type: "descriptive",
    subject: 3,
    difficulty: "hard",
    marks: 10,
    createdAt: "2023-05-17T09:15:00Z",
    updatedAt: "2023-05-17T09:15:00Z",
    createdBy: "1",
    status: "active",
    tags: ["database", "normalization"],
    answer:
      "Normalization is the process of organizing data in a database to reduce redundancy and improve data integrity.",
  },
  {
    id: 4,
    text: "What does SQL stand for?",
    type: "short_answer",
    subject: 3,
    difficulty: "easy",
    marks: 1,
    createdAt: "2023-05-22T09:30:00Z",
    updatedAt: "2023-05-22T09:30:00Z",
    createdBy: "1",
    status: "active",
    tags: ["sql", "database"],
    answer: "Structured Query Language",
  },
  {
    id: 5,
    text: "A primary key can contain NULL values.",
    type: "true_false",
    subject: 3,
    difficulty: "easy",
    marks: 1,
    createdAt: "2023-05-23T10:00:00Z",
    updatedAt: "2023-05-23T10:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["database", "primary key"],
    correctAnswer: false,
  },
  {
    id: 6,
    text: "Which SQL command is used to retrieve data from a database?",
    type: "mcq",
    subject: 3,
    difficulty: "easy",
    marks: 2,
    createdAt: "2023-05-24T11:00:00Z",
    updatedAt: "2023-05-24T11:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["sql", "select"],
    options: [
      { id: 1, text: "GET", isCorrect: false },
      { id: 2, text: "SELECT", isCorrect: true },
      { id: 3, text: "RETRIEVE", isCorrect: false },
      { id: 4, text: "FETCH", isCorrect: false },
    ],
  },
  {
    id: 7,
    text: "Define ACID properties in database transactions.",
    type: "descriptive",
    subject: 3,
    difficulty: "hard",
    marks: 8,
    createdAt: "2023-05-25T12:00:00Z",
    updatedAt: "2023-05-25T12:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["database", "acid", "transactions"],
    answer:
      "ACID stands for Atomicity, Consistency, Isolation, and Durability - the four key properties that guarantee reliable database transactions.",
  },
  {
    id: 8,
    text: "What is the difference between DELETE and TRUNCATE commands?",
    type: "descriptive",
    subject: 3,
    difficulty: "medium",
    marks: 5,
    createdAt: "2023-05-26T13:00:00Z",
    updatedAt: "2023-05-26T13:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["sql", "delete", "truncate"],
    answer:
      "DELETE removes specific rows and can be rolled back, while TRUNCATE removes all rows and cannot be rolled back.",
  },
  {
    id: 9,
    text: "Which normal form eliminates transitive dependencies?",
    type: "mcq",
    subject: 3,
    difficulty: "medium",
    marks: 2,
    createdAt: "2023-05-27T14:00:00Z",
    updatedAt: "2023-05-27T14:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["normalization", "3nf"],
    options: [
      { id: 1, text: "First Normal Form (1NF)", isCorrect: false },
      { id: 2, text: "Second Normal Form (2NF)", isCorrect: false },
      { id: 3, text: "Third Normal Form (3NF)", isCorrect: true },
      { id: 4, text: "Boyce-Codd Normal Form (BCNF)", isCorrect: false },
    ],
  },
  {
    id: 10,
    text: "A foreign key can reference multiple tables.",
    type: "true_false",
    subject: 3,
    difficulty: "medium",
    marks: 1,
    createdAt: "2023-05-28T15:00:00Z",
    updatedAt: "2023-05-28T15:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["foreign key", "database"],
    correctAnswer: false,
  },
  {
    id: 11,
    text: "Explain the concept of database indexing and its benefits.",
    type: "descriptive",
    subject: 3,
    difficulty: "medium",
    marks: 6,
    createdAt: "2023-05-29T16:00:00Z",
    updatedAt: "2023-05-29T16:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["indexing", "performance"],
    answer:
      "Database indexing creates data structures that improve query performance by providing faster access paths to data.",
  },
  {
    id: 12,
    text: "Which JOIN returns all records from both tables?",
    type: "mcq",
    subject: 3,
    difficulty: "medium",
    marks: 2,
    createdAt: "2023-05-30T17:00:00Z",
    updatedAt: "2023-05-30T17:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["sql", "joins"],
    options: [
      { id: 1, text: "INNER JOIN", isCorrect: false },
      { id: 2, text: "LEFT JOIN", isCorrect: false },
      { id: 3, text: "RIGHT JOIN", isCorrect: false },
      { id: 4, text: "FULL OUTER JOIN", isCorrect: true },
    ],
  },
  {
    id: 13,
    text: "What is a stored procedure?",
    type: "short_answer",
    subject: 3,
    difficulty: "medium",
    marks: 3,
    createdAt: "2023-05-31T18:00:00Z",
    updatedAt: "2023-05-31T18:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["stored procedure", "database"],
    answer: "A stored procedure is a precompiled collection of SQL statements stored in the database.",
  },
  {
    id: 14,
    text: "Database views can be updated directly.",
    type: "true_false",
    subject: 3,
    difficulty: "medium",
    marks: 1,
    createdAt: "2023-06-01T19:00:00Z",
    updatedAt: "2023-06-01T19:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["views", "database"],
    correctAnswer: false,
  },
  {
    id: 15,
    text: "Describe the differences between clustered and non-clustered indexes.",
    type: "descriptive",
    subject: 3,
    difficulty: "hard",
    marks: 8,
    createdAt: "2023-06-02T20:00:00Z",
    updatedAt: "2023-06-02T20:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["indexing", "clustered", "non-clustered"],
    answer:
      "Clustered indexes physically reorder table data, while non-clustered indexes create separate structures pointing to data rows.",
  },

  // Data Structures Questions (16-30)
  {
    id: 16,
    text: "Which data structure is used for implementing a priority queue?",
    type: "mcq",
    subject: 2,
    difficulty: "medium",
    marks: 2,
    createdAt: "2023-05-18T11:30:00Z",
    updatedAt: "2023-05-18T11:30:00Z",
    createdBy: "1",
    status: "active",
    tags: ["data structures", "priority queue"],
    options: [
      { id: 1, text: "Stack", isCorrect: false },
      { id: 2, text: "Queue", isCorrect: false },
      { id: 3, text: "Heap", isCorrect: true },
      { id: 4, text: "Linked List", isCorrect: false },
    ],
  },
  {
    id: 17,
    text: "What is the time complexity of binary search?",
    type: "mcq",
    subject: 2,
    difficulty: "medium",
    marks: 2,
    createdAt: "2023-05-20T10:00:00Z",
    updatedAt: "2023-05-20T10:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["algorithms", "complexity"],
    options: [
      { id: 1, text: "O(n)", isCorrect: false },
      { id: 2, text: "O(log n)", isCorrect: true },
      { id: 3, text: "O(n²)", isCorrect: false },
      { id: 4, text: "O(1)", isCorrect: false },
    ],
  },
  {
    id: 18,
    text: "Explain the difference between a stack and a queue.",
    type: "descriptive",
    subject: 2,
    difficulty: "easy",
    marks: 4,
    createdAt: "2023-06-03T09:00:00Z",
    updatedAt: "2023-06-03T09:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["stack", "queue", "data structures"],
    answer:
      "Stack follows LIFO (Last In First Out) principle, while Queue follows FIFO (First In First Out) principle.",
  },
  {
    id: 19,
    text: "A binary tree with n nodes has exactly n-1 edges.",
    type: "true_false",
    subject: 2,
    difficulty: "easy",
    marks: 1,
    createdAt: "2023-06-04T10:00:00Z",
    updatedAt: "2023-06-04T10:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["binary tree", "graph theory"],
    correctAnswer: true,
  },
  {
    id: 20,
    text: "What is the worst-case time complexity of quicksort?",
    type: "mcq",
    subject: 2,
    difficulty: "medium",
    marks: 2,
    createdAt: "2023-06-05T11:00:00Z",
    updatedAt: "2023-06-05T11:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["sorting", "quicksort", "complexity"],
    options: [
      { id: 1, text: "O(n log n)", isCorrect: false },
      { id: 2, text: "O(n²)", isCorrect: true },
      { id: 3, text: "O(n)", isCorrect: false },
      { id: 4, text: "O(log n)", isCorrect: false },
    ],
  },
  {
    id: 21,
    text: "Describe the process of inserting an element into a binary search tree.",
    type: "descriptive",
    subject: 2,
    difficulty: "medium",
    marks: 6,
    createdAt: "2023-06-06T12:00:00Z",
    updatedAt: "2023-06-06T12:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["bst", "insertion", "trees"],
    answer:
      "Start at root, compare with current node, go left if smaller or right if larger, insert at empty position.",
  },
  {
    id: 22,
    text: "What is a hash collision?",
    type: "short_answer",
    subject: 2,
    difficulty: "medium",
    marks: 3,
    createdAt: "2023-06-07T13:00:00Z",
    updatedAt: "2023-06-07T13:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["hashing", "collision"],
    answer: "When two different keys produce the same hash value.",
  },
  {
    id: 23,
    text: "Linked lists provide constant time random access to elements.",
    type: "true_false",
    subject: 2,
    difficulty: "easy",
    marks: 1,
    createdAt: "2023-06-08T14:00:00Z",
    updatedAt: "2023-06-08T14:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["linked list", "access time"],
    correctAnswer: false,
  },
  {
    id: 24,
    text: "Which traversal method visits the root node first?",
    type: "mcq",
    subject: 2,
    difficulty: "easy",
    marks: 2,
    createdAt: "2023-06-09T15:00:00Z",
    updatedAt: "2023-06-09T15:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["tree traversal", "preorder"],
    options: [
      { id: 1, text: "Inorder", isCorrect: false },
      { id: 2, text: "Preorder", isCorrect: true },
      { id: 3, text: "Postorder", isCorrect: false },
      { id: 4, text: "Level order", isCorrect: false },
    ],
  },
  {
    id: 25,
    text: "Explain the concept of dynamic programming with an example.",
    type: "descriptive",
    subject: 2,
    difficulty: "hard",
    marks: 10,
    createdAt: "2023-06-10T16:00:00Z",
    updatedAt: "2023-06-10T16:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["dynamic programming", "algorithms"],
    answer:
      "Dynamic programming solves complex problems by breaking them into simpler subproblems and storing results to avoid redundant calculations. Example: Fibonacci sequence.",
  },
  {
    id: 26,
    text: "What is the space complexity of merge sort?",
    type: "short_answer",
    subject: 2,
    difficulty: "medium",
    marks: 2,
    createdAt: "2023-06-11T17:00:00Z",
    updatedAt: "2023-06-11T17:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["merge sort", "space complexity"],
    answer: "O(n)",
  },
  {
    id: 27,
    text: "A complete binary tree can be efficiently represented using an array.",
    type: "true_false",
    subject: 2,
    difficulty: "medium",
    marks: 1,
    createdAt: "2023-06-12T18:00:00Z",
    updatedAt: "2023-06-12T18:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["binary tree", "array representation"],
    correctAnswer: true,
  },
  {
    id: 28,
    text: "Which data structure is best for implementing undo functionality?",
    type: "mcq",
    subject: 2,
    difficulty: "easy",
    marks: 2,
    createdAt: "2023-06-13T19:00:00Z",
    updatedAt: "2023-06-13T19:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["stack", "undo", "applications"],
    options: [
      { id: 1, text: "Queue", isCorrect: false },
      { id: 2, text: "Stack", isCorrect: true },
      { id: 3, text: "Array", isCorrect: false },
      { id: 4, text: "Linked List", isCorrect: false },
    ],
  },
  {
    id: 29,
    text: "Describe Dijkstra's algorithm for finding shortest paths.",
    type: "descriptive",
    subject: 2,
    difficulty: "hard",
    marks: 8,
    createdAt: "2023-06-14T20:00:00Z",
    updatedAt: "2023-06-14T20:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["dijkstra", "shortest path", "graphs"],
    answer:
      "Dijkstra's algorithm finds shortest paths from a source vertex to all other vertices in a weighted graph using a greedy approach with a priority queue.",
  },
  {
    id: 30,
    text: "What is the average case time complexity of hash table operations?",
    type: "short_answer",
    subject: 2,
    difficulty: "medium",
    marks: 2,
    createdAt: "2023-06-15T21:00:00Z",
    updatedAt: "2023-06-15T21:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["hash table", "time complexity"],
    answer: "O(1)",
  },

  // Programming Questions (31-50)
  {
    id: 31,
    text: "Is Python a compiled language?",
    type: "true_false",
    subject: 1,
    difficulty: "easy",
    marks: 1,
    createdAt: "2023-05-19T13:20:00Z",
    updatedAt: "2023-05-19T13:20:00Z",
    createdBy: "1",
    status: "active",
    tags: ["programming", "python"],
    correctAnswer: false,
  },
  {
    id: 32,
    text: "Explain the concept of inheritance in object-oriented programming.",
    type: "descriptive",
    subject: 1,
    difficulty: "medium",
    marks: 8,
    createdAt: "2023-05-21T11:00:00Z",
    updatedAt: "2023-05-21T11:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["oop", "inheritance"],
    answer: "Inheritance is a mechanism where a new class inherits properties and methods from an existing class.",
  },
  {
    id: 33,
    text: "Which of the following is NOT a primitive data type in Java?",
    type: "mcq",
    subject: 1,
    difficulty: "easy",
    marks: 2,
    createdAt: "2023-06-16T09:00:00Z",
    updatedAt: "2023-06-16T09:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["java", "data types"],
    options: [
      { id: 1, text: "int", isCorrect: false },
      { id: 2, text: "boolean", isCorrect: false },
      { id: 3, text: "String", isCorrect: true },
      { id: 4, text: "char", isCorrect: false },
    ],
  },
  {
    id: 34,
    text: "What is polymorphism in OOP?",
    type: "short_answer",
    subject: 1,
    difficulty: "medium",
    marks: 4,
    createdAt: "2023-06-17T10:00:00Z",
    updatedAt: "2023-06-17T10:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["oop", "polymorphism"],
    answer:
      "The ability of objects of different types to be treated as instances of the same type through a common interface.",
  },
  {
    id: 35,
    text: "Variables in Python are dynamically typed.",
    type: "true_false",
    subject: 1,
    difficulty: "easy",
    marks: 1,
    createdAt: "2023-06-18T11:00:00Z",
    updatedAt: "2023-06-18T11:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["python", "typing"],
    correctAnswer: true,
  },
  {
    id: 36,
    text: "Which loop is guaranteed to execute at least once?",
    type: "mcq",
    subject: 1,
    difficulty: "easy",
    marks: 2,
    createdAt: "2023-06-19T12:00:00Z",
    updatedAt: "2023-06-19T12:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["loops", "control structures"],
    options: [
      { id: 1, text: "for loop", isCorrect: false },
      { id: 2, text: "while loop", isCorrect: false },
      { id: 3, text: "do-while loop", isCorrect: true },
      { id: 4, text: "foreach loop", isCorrect: false },
    ],
  },
  {
    id: 37,
    text: "Describe the difference between method overloading and method overriding.",
    type: "descriptive",
    subject: 1,
    difficulty: "medium",
    marks: 6,
    createdAt: "2023-06-20T13:00:00Z",
    updatedAt: "2023-06-20T13:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["oop", "overloading", "overriding"],
    answer:
      "Overloading is multiple methods with same name but different parameters. Overriding is redefining a parent class method in a child class.",
  },
  {
    id: 38,
    text: "What is the purpose of a constructor in a class?",
    type: "short_answer",
    subject: 1,
    difficulty: "easy",
    marks: 3,
    createdAt: "2023-06-21T14:00:00Z",
    updatedAt: "2023-06-21T14:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["oop", "constructor"],
    answer: "To initialize object state when an instance of the class is created.",
  },
  {
    id: 39,
    text: "Abstract classes can be instantiated directly.",
    type: "true_false",
    subject: 1,
    difficulty: "medium",
    marks: 1,
    createdAt: "2023-06-22T15:00:00Z",
    updatedAt: "2023-06-22T15:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["oop", "abstract classes"],
    correctAnswer: false,
  },
  {
    id: 40,
    text: "Which access modifier provides the most restrictive access?",
    type: "mcq",
    subject: 1,
    difficulty: "easy",
    marks: 2,
    createdAt: "2023-06-23T16:00:00Z",
    updatedAt: "2023-06-23T16:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["access modifiers", "encapsulation"],
    options: [
      { id: 1, text: "public", isCorrect: false },
      { id: 2, text: "protected", isCorrect: false },
      { id: 3, text: "private", isCorrect: true },
      { id: 4, text: "default", isCorrect: false },
    ],
  },
  {
    id: 41,
    text: "Explain the concept of exception handling in programming.",
    type: "descriptive",
    subject: 1,
    difficulty: "medium",
    marks: 7,
    createdAt: "2023-06-24T17:00:00Z",
    updatedAt: "2023-06-24T17:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["exception handling", "error handling"],
    answer:
      "Exception handling is a programming construct that allows programs to respond to exceptional circumstances during execution using try-catch blocks.",
  },
  {
    id: 42,
    text: "What is recursion?",
    type: "short_answer",
    subject: 1,
    difficulty: "medium",
    marks: 3,
    createdAt: "2023-06-25T18:00:00Z",
    updatedAt: "2023-06-25T18:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["recursion", "algorithms"],
    answer: "A programming technique where a function calls itself to solve a problem.",
  },
  {
    id: 43,
    text: "Static methods can access instance variables directly.",
    type: "true_false",
    subject: 1,
    difficulty: "medium",
    marks: 1,
    createdAt: "2023-06-26T19:00:00Z",
    updatedAt: "2023-06-26T19:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["static methods", "oop"],
    correctAnswer: false,
  },
  {
    id: 44,
    text: "Which of the following is a characteristic of functional programming?",
    type: "mcq",
    subject: 1,
    difficulty: "medium",
    marks: 2,
    createdAt: "2023-06-27T20:00:00Z",
    updatedAt: "2023-06-27T20:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["functional programming", "paradigms"],
    options: [
      { id: 1, text: "Mutable state", isCorrect: false },
      { id: 2, text: "Side effects", isCorrect: false },
      { id: 3, text: "Pure functions", isCorrect: true },
      { id: 4, text: "Global variables", isCorrect: false },
    ],
  },
  {
    id: 45,
    text: "Describe the Model-View-Controller (MVC) architectural pattern.",
    type: "descriptive",
    subject: 1,
    difficulty: "hard",
    marks: 10,
    createdAt: "2023-06-28T21:00:00Z",
    updatedAt: "2023-06-28T21:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["mvc", "design patterns", "architecture"],
    answer:
      "MVC separates application logic into three interconnected components: Model (data), View (presentation), and Controller (user input handling).",
  },
  {
    id: 46,
    text: "What is the difference between compilation and interpretation?",
    type: "short_answer",
    subject: 1,
    difficulty: "medium",
    marks: 4,
    createdAt: "2023-06-29T22:00:00Z",
    updatedAt: "2023-06-29T22:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["compilation", "interpretation"],
    answer:
      "Compilation translates entire source code to machine code before execution, while interpretation executes code line by line.",
  },
  {
    id: 47,
    text: "Interfaces in Java can contain method implementations.",
    type: "true_false",
    subject: 1,
    difficulty: "medium",
    marks: 1,
    createdAt: "2023-06-30T23:00:00Z",
    updatedAt: "2023-06-30T23:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["java", "interfaces"],
    correctAnswer: true,
  },
  {
    id: 48,
    text: "Which design pattern ensures a class has only one instance?",
    type: "mcq",
    subject: 1,
    difficulty: "medium",
    marks: 2,
    createdAt: "2023-07-01T09:00:00Z",
    updatedAt: "2023-07-01T09:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["design patterns", "singleton"],
    options: [
      { id: 1, text: "Factory", isCorrect: false },
      { id: 2, text: "Singleton", isCorrect: true },
      { id: 3, text: "Observer", isCorrect: false },
      { id: 4, text: "Strategy", isCorrect: false },
    ],
  },
  {
    id: 49,
    text: "Explain the concept of garbage collection in programming languages.",
    type: "descriptive",
    subject: 1,
    difficulty: "medium",
    marks: 6,
    createdAt: "2023-07-02T10:00:00Z",
    updatedAt: "2023-07-02T10:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["garbage collection", "memory management"],
    answer:
      "Garbage collection is automatic memory management that reclaims memory occupied by objects that are no longer reachable or referenced.",
  },
  {
    id: 50,
    text: "What is the time complexity of accessing an element in an array by index?",
    type: "short_answer",
    subject: 1,
    difficulty: "easy",
    marks: 1,
    createdAt: "2023-07-03T11:00:00Z",
    updatedAt: "2023-07-03T11:00:00Z",
    createdBy: "1",
    status: "active",
    tags: ["arrays", "time complexity"],
    answer: "O(1)",
  },
]

// Mock question groups
export const initialQuestionGroups: QuestionGroup[] = [
  {
    id: 1,
    title: "Database Fundamentals",
    description: "Basic concepts and principles of database systems",
    tags: ["database", "fundamentals", "introduction"],
    subject: 3,
    difficulty: "easy",
    intendedUsage: "Midterm Examination",
    questions: [1, 2, 4, 5, 6],
    createdAt: "2023-05-21T09:00:00Z",
    updatedAt: "2023-05-21T09:00:00Z",
    createdBy: "1",
  },
  {
    id: 2,
    title: "Advanced Database Topics",
    description: "Complex database concepts including normalization and optimization",
    tags: ["database", "advanced", "normalization"],
    subject: 3,
    difficulty: "hard",
    intendedUsage: "Final Examination",
    questions: [3, 7, 9, 11, 15],
    createdAt: "2023-05-22T11:00:00Z",
    updatedAt: "2023-05-22T11:00:00Z",
    createdBy: "1",
  },
  {
    id: 3,
    title: "Data Structures & Algorithms",
    description: "Core concepts in data structures and algorithm analysis",
    tags: ["data structures", "algorithms", "complexity"],
    subject: 2,
    difficulty: "medium",
    intendedUsage: "Quiz",
    questions: [16, 17, 20, 25, 29],
    createdAt: "2023-05-23T14:00:00Z",
    updatedAt: "2023-05-23T14:00:00Z",
    createdBy: "1",
  },
]

// Mock data for batches
export const batches = [
  { id: 1, name: "BSCS-2021", course: "BSCS", department: "Computer Science", year: 2021, students: 45 },
  { id: 2, name: "BSCS-2022", course: "BSCS", department: "Computer Science", year: 2022, students: 52 },
  { id: 3, name: "BSCS-2023", course: "BSCS", department: "Computer Science", year: 2023, students: 48 },
  { id: 4, name: "BSCS-2024", course: "BSCS", department: "Computer Science", year: 2024, students: 55 },
]

// Get current date and create realistic exam dates
const now = new Date()
const tomorrow = new Date(now)
tomorrow.setDate(now.getDate() + 1)
const nextWeek = new Date(now)
nextWeek.setDate(now.getDate() + 7)

// Format dates for exam data
const formatDate = (date: Date) => date.toISOString().split("T")[0]

// Mock exams data with comprehensive question sets
export const initialExams: Exam[] = [
  {
    id: 1,
    title: "Comprehensive Database Systems Exam",
    description:
      "Final examination covering all aspects of database systems including design, SQL, normalization, and advanced topics",
    subject: 3,
    course: "BSCS",
    batches: [1, 2],
    totalMarks: 150,
    duration: 180, // 3 hours
    startDate: formatDate(tomorrow),
    startTime: "09:00",
    endDate: formatDate(tomorrow),
    endTime: "12:00",
    instructions:
      "Read all questions carefully. Answer all questions within the time limit. Use proper SQL syntax where applicable. Webcam monitoring is active throughout the exam. Do not use external resources. Show all work for partial credit.",
    allowedAttempts: 1,
    status: "scheduled",
    questions: Array.from({ length: 50 }, (_, i) => i + 1), // All 50 questions for comprehensive testing
    invigilator: 1,
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-15T10:30:00Z",
    createdBy: "1",
    studentsEnrolled: 97,
    studentsCompleted: 0,
    averageScore: 0,
  },
  {
    id: 2,
    title: "Programming Fundamentals Quiz",
    description: "Quick assessment covering basic programming concepts and OOP principles",
    subject: 1,
    course: "BSCS",
    batches: [3, 4],
    totalMarks: 25,
    duration: 45,
    startDate: formatDate(new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000)),
    startTime: "14:00",
    endDate: formatDate(new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000)),
    endTime: "14:45",
    instructions: "This is a timed quiz. Answer all questions within the time limit. No external resources allowed.",
    allowedAttempts: 2,
    status: "scheduled",
    questions: [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
    invigilator: 1,
    createdAt: "2024-01-20T14:30:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
    createdBy: "1",
    studentsEnrolled: 103,
    studentsCompleted: 0,
    averageScore: 0,
  },
  {
    id: 3,
    title: "Data Structures Final Exam",
    description: "Comprehensive final examination covering all data structures, algorithms, and complexity analysis",
    subject: 2,
    course: "BSCS",
    batches: [1, 2],
    totalMarks: 100,
    duration: 120,
    startDate: formatDate(nextWeek),
    startTime: "10:00",
    endDate: formatDate(nextWeek),
    endTime: "12:00",
    instructions:
      "Final examination covering all course topics. Show all work for partial credit. Webcam monitoring is active.",
    allowedAttempts: 1,
    status: "scheduled",
    questions: [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
    invigilator: 2,
    createdAt: "2024-02-01T09:00:00Z",
    updatedAt: "2024-02-01T09:00:00Z",
    createdBy: "2",
    studentsEnrolled: 145,
    studentsCompleted: 0,
    averageScore: 0,
  },
]

// Mock exam requests with realistic data
export const examRequests: ExamRequest[] = [
  {
    id: 1,
    examId: 1,
    studentId: "231001001447",
    studentName: "John Doe",
    batch: "BSCS-2021",
    requestTime: new Date(tomorrow.getTime() - 8 * 60 * 1000).toISOString(),
    status: "approved",
    verificationNotes: "Student verified present in classroom, webcam working properly",
    approvedBy: 1,
    approvedAt: new Date(tomorrow.getTime() - 7 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    examId: 1,
    studentId: "231001001448",
    studentName: "Jane Smith",
    batch: "BSCS-2021",
    requestTime: new Date(tomorrow.getTime() - 9 * 60 * 1000).toISOString(),
    status: "approved",
    verificationNotes: "Student verified present in classroom, webcam working properly",
    approvedBy: 1,
    approvedAt: new Date(tomorrow.getTime() - 7 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    examId: 1,
    studentId: "231001001449",
    studentName: "Mike Johnson",
    batch: "BSCS-2022",
    requestTime: new Date(tomorrow.getTime() - 6 * 60 * 1000).toISOString(),
    status: "pending",
  },
  {
    id: 4,
    examId: 1,
    studentId: "231001001450",
    studentName: "Alice Brown",
    batch: "BSCS-2021",
    requestTime: new Date(tomorrow.getTime() - 5 * 60 * 1000).toISOString(),
    status: "approved",
    verificationNotes: "Student present, all systems verified",
    approvedBy: 1,
    approvedAt: new Date(tomorrow.getTime() - 4 * 60 * 1000).toISOString(),
  },
]

// Mock active student sessions for live monitoring demo
export const studentSessions: StudentSession[] = [
  {
    id: 1,
    examId: 1,
    studentId: "231001001447",
    studentName: "John Doe",
    batch: "BSCS-2021",
    startTime: new Date(now.getTime() - 45 * 60 * 1000).toISOString(),
    status: "active",
    cheatingAlerts: [],
    lastActivity: new Date(now.getTime() - 2 * 60 * 1000).toISOString(),
    answers: {
      1: "A database management system (DBMS) is software that handles the storage, retrieval, and management of data in a database.",
      2: 4,
      5: false,
      6: 2,
      31: false,
      33: 3,
    },
  },
  {
    id: 2,
    examId: 1,
    studentId: "231001001448",
    studentName: "Jane Smith",
    batch: "BSCS-2021",
    startTime: new Date(now.getTime() - 50 * 60 * 1000).toISOString(),
    status: "active",
    cheatingAlerts: [
      {
        id: 1,
        sessionId: 2,
        examId: 1,
        studentId: "231001001448",
        type: "looking_away",
        severity: "medium",
        timestamp: new Date(now.getTime() - 20 * 60 * 1000).toISOString(),
        confidence: 0.76,
        description: "Student looking away from screen frequently",
        resolved: false,
      },
    ],
    lastActivity: new Date(now.getTime() - 1 * 60 * 1000).toISOString(),
    answers: {
      1: "DBMS is software for managing databases",
      2: 4,
      4: "Structured Query Language",
      5: false,
      16: 3,
      17: 2,
    },
  },
]

// Mock audit logs for comprehensive tracking
export const auditLogs: AuditLog[] = [
  {
    id: 1,
    action: "EXAM_REQUEST_SUBMITTED",
    entityType: "exam",
    entityId: 1,
    userId: "231001001447",
    userName: "John Doe",
    changes: { examId: 1, status: "pending" },
    timestamp: new Date(tomorrow.getTime() - 8 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    action: "EXAM_REQUEST_APPROVED",
    entityType: "exam",
    entityId: 1,
    userId: "1",
    userName: "Dr. Sarah Johnson",
    changes: { studentId: "231001001447", status: "approved", verificationNotes: "Student verified present" },
    timestamp: new Date(tomorrow.getTime() - 7 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    action: "EXAM_SESSION_STARTED",
    entityType: "session",
    entityId: 1,
    userId: "231001001447",
    userName: "John Doe",
    changes: { examId: 1, webcamEnabled: true, fullscreenEnabled: true },
    timestamp: new Date(now.getTime() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 4,
    action: "CHEATING_DETECTED",
    entityType: "alert",
    entityId: 1,
    userId: "231001001448",
    userName: "Jane Smith",
    changes: { type: "looking_away", severity: "medium", confidence: 0.76 },
    timestamp: new Date(now.getTime() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: 5,
    action: "ANSWER_SUBMITTED",
    entityType: "session",
    entityId: 1,
    userId: "231001001447",
    userName: "John Doe",
    changes: { questionId: 1, answerType: "descriptive", autoSaved: true },
    timestamp: new Date(now.getTime() - 30 * 60 * 1000).toISOString(),
  },
]
